'use client';

import React, { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import { Loader2, Smartphone, Box, ArrowLeft } from 'lucide-react';
import Link from 'next/link';

export default function ARViewerPage() {
    const params = useParams();
    const jobId = params.id as string;
    const [modelUrl, setModelUrl] = useState<string | null>(null);
    const [status, setStatus] = useState<'loading' | 'ready' | 'error'>('loading');

    useEffect(() => {
        // Required for model-viewer to work
        const script = document.createElement('script');
        script.type = 'module';
        script.src = 'https://ajax.googleapis.com/ajax/libs/model-viewer/3.5.0/model-viewer.min.js';
        document.head.appendChild(script);

        const fetchStatus = async () => {
            try {
                const res = await fetch(`/api/status/${jobId}`);
                const data = await res.json();
                if (data.Status === 'SUCCESS' || jobId.startsWith('demo-')) {
                    setModelUrl(data.ResultUrl);
                    setStatus('ready');
                } else {
                    setStatus('error');
                }
            } catch (err) {
                console.error('AR Load Error:', err);
                setStatus('error');
            }
        };

        fetchStatus();
    }, [jobId]);

    if (status === 'loading') {
        return (
            <div className="fixed inset-0 bg-white flex flex-col items-center justify-center p-6 text-center">
                <Loader2 className="w-10 h-10 animate-spin text-accent mb-4" />
                <h1 className="text-xl font-bold">Preparing AR Experience</h1>
                <p className="text-zinc-500 mt-2">Connecting to 3DGen AI...</p>
            </div>
        );
    }

    if (status === 'error' || !modelUrl) {
        return (
            <div className="fixed inset-0 bg-white flex flex-col items-center justify-center p-6 text-center">
                <Box className="w-16 h-16 text-zinc-300 mb-6" />
                <h1 className="text-xl font-bold text-red-600">Model Not Found</h1>
                <p className="text-zinc-500 mt-2">This link may have expired or the job is still processing.</p>
                <Link href="/dashboard" className="mt-8 px-6 py-3 bg-black text-white rounded-2xl font-bold">
                    Go to Dashboard
                </Link>
            </div>
        );
    }

    return (
        <div className="fixed inset-0 bg-white flex flex-col overflow-hidden">
            {/* Header */}
            <header className="p-4 flex items-center justify-between border-b border-zinc-100 bg-white/80 backdrop-blur-md z-10">
                <div className="flex items-center gap-3">
                    <div className="w-8 h-8 bg-black rounded-lg flex items-center justify-center">
                        <Box className="w-5 h-5 text-white" />
                    </div>
                    <span className="font-bold tracking-tight">3DGen AI AR</span>
                </div>
                <Link href="/dashboard" className="text-sm font-medium text-zinc-500 flex items-center gap-1">
                    <ArrowLeft className="w-4 h-4" />
                    Dashboard
                </Link>
            </header>

            {/* Viewer Section */}
            <div className="flex-grow relative">
                {/* @ts-ignore */}
                <model-viewer
                    src={modelUrl}
                    poster="/next.svg"
                    alt="A 3D model generated by 3DGen AI"
                    shadow-intensity="1"
                    camera-controls
                    touch-action="pan-y"
                    ar
                    ar-modes="webxr scene-viewer quick-look"
                    style={{ width: '100%', height: '100%' }}
                >
                    <button
                        slot="ar-button"
                        className="absolute bottom-10 left-1/2 -translate-x-1/2 px-8 py-4 bg-black text-white rounded-full font-bold shadow-2xl flex items-center gap-3 active:scale-95 transition-transform"
                    >
                        <Smartphone className="w-5 h-5" />
                        View in Your Space
                    </button>

                    <div className="absolute bottom-4 left-0 right-0 text-center pointer-events-none">
                        <p className="text-[10px] text-zinc-400 font-bold uppercase tracking-widest">
                            Native AR Powered by Google Cloud
                        </p>
                    </div>
                    {/* @ts-ignore */}
                </model-viewer>
            </div>

            {/* Footer / Info */}
            <div className="p-6 bg-zinc-50 border-t border-zinc-100">
                <h3 className="font-bold text-lg mb-1">AR Preview Ready</h3>
                <p className="text-sm text-zinc-500">
                    Interact with the model above or tap the button to place it in your real-world environment.
                </p>
            </div>
        </div>
    );
}
